### PR TITLE
A bunch of edits & corrections.

### PR DESCRIPTION
**Pull request by riggs**
Mostly small, a few bigger ones for clarity.

### CODE REVIEW

**Comment by browniefed** [comment]
Uhm wow, this is awesome. Thank you for taking the time to do this.
I'll review them in about an hour and get things merged and published.
🔥 🔥 🔥

**Comment by riggs** [comment]
Hey, thanks for writing it in the first place. I just went through and cleaned stuff up as I was going through the thing. I'll probably have a bunch more when I finish going through it.

**Comment by browniefed** [comment]
Thanks again, not the greatest writer, so appreciate the cleaning up of my writing.

**Comment by browniefed** [comment]
Latest changes should be deployed

**Pull request merged**
